### ISSUE TITLE
cmd＋enterで投稿機能

### ISSUE THREAD

**Issue by Sp00kyDog** [Sp00kyDog/study_from_python#11]
表題の通り
今後ショートカットコマンド追加するならここはクラス化したいかも？

**Comment by Ryanryanjp** [comment]
クラス化未だによくわかんないのでとりあえず動くの実装してみますね。

**Comment by Ryanryanjp** [comment]
http://myenigma.hatenablog.com/entry/2016/01/24/113413
同時押しの処理メニューバー作らないとダメっぽい？
ので寝て起きたら試します。

**Comment by Ryanryanjp** [comment]
http://kagring.blog.fc2.com/blog-entry-88.html
今まで使ってきたQWidgetとこれから使いはじめるQMainWindowで仕様が違いすぎてマジつらぽよだったけど
どうやらQMainWindowにQWidgetを置けるっぽいことがわかった（ただしソースはC++の記事）
寝て起きたら試す。

**Comment by Ryanryanjp** [comment]
http://stackoverflow.com/questions/30143913/qwidget-cannot-display-on-qmainwindow-instance-pyqt5
ぴったんこカン・カンな記事があった。外人はマジ偉い。

**Comment by Ryanryanjp** [comment]
実装してプルリクエスト送りました。
