### ISSUE TITLE
コールできない

### ISSUE THREAD

**Issue by Sp00kyDog** [Sp00kyDog/study_from_python#5]
ついクラス読込→インスタンス化→スロット設定→えらー！
どうすればスロットにインスタンス化したの組み込める？

**Comment by Ryanryanjp** [comment]
コード貼ってくれ～～

**Comment by Ryanryanjp** [comment]
returnするんじゃなくてlabel作成する必要がありましたね...

**Comment by Sp00kyDog** [comment]
デバッグしてりゃすぐ気づけたな環境がない。。。

**Comment by Ryanryanjp** [comment]
解決したんでIssues閉じていいっすね
